package com.example.smartalarm.feature.clock.framework.di

import com.example.smartalarm.BuildConfig
import com.example.smartalarm.feature.clock.data.remote.api.GeoApifyApiService
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import okhttp3.Interceptor
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import javax.inject.Singleton



/**
 * Hilt Module that provides networking dependencies for the application.
 * * This module configures [Retrofit], [OkHttpClient], and [Gson] to facilitate
 * communication with the Geoapify APIs.
 */
@Module
@InstallIn(SingletonComponent::class)
object RemoteModule {


    private const val API_PARAM_KEY = "apiKey"
    private const val GEO_APIFY_BASE_URL = "https://api.geoapify.com/"


    /**
     * Provides a [Gson] instance used for JSON serialization and deserialization.
     */
    @Provides
    @Singleton
    fun provideGson(): Gson = GsonBuilder().create()

    /**
     * Provides an [HttpLoggingInterceptor] to log HTTP request and response data
     * in the Logcat. Useful for debugging network traffic.
     */
    @Provides
    @Singleton
    fun provideLoggingInterceptor(): HttpLoggingInterceptor =
        HttpLoggingInterceptor().apply {
            level = HttpLoggingInterceptor.Level.BODY
        }

    /**
     * Provides an [Interceptor] that automatically appends the Geoapify API key
     * as a query parameter to every outgoing request.
     * * This ensures that API calls are authenticated without needing to pass
     * the key manually in the service methods.
     */
    @Provides
    @Singleton
    fun provideGeoApifyApiKeyInterceptor(): Interceptor = Interceptor { chain ->
        val original = chain.request()
        val originalHttpUrl = original.url

        val newUrl = originalHttpUrl.newBuilder()
            .addQueryParameter(API_PARAM_KEY, BuildConfig.GEO_APIFY_API_KEY)
            .build()

        val newRequest = original.newBuilder()
            .url(newUrl)
            .build()

        chain.proceed(newRequest)
    }

    /**
     * Provides a configured [OkHttpClient].
     * * @param loggingInterceptor Logs network activity.
     * @param apiKeyInterceptor Appends the necessary API authentication.
     */
    @Provides
    @Singleton
    fun provideOkHttpClient(
        loggingInterceptor: HttpLoggingInterceptor,
        apiKeyInterceptor: Interceptor
    ): OkHttpClient = OkHttpClient.Builder()
        .addInterceptor(apiKeyInterceptor)
        .addInterceptor(loggingInterceptor)
        .build()

    /**
     * Provides a [Retrofit] instance configured with the Geoapify base URL,
     * the [OkHttpClient], and a [Gson] converter.
     */
    @Provides
    @Singleton
    fun provideRetrofit(
        okHttpClient: OkHttpClient,
        gson: Gson
    ): Retrofit = Retrofit.Builder()
        .baseUrl(GEO_APIFY_BASE_URL)
        .addConverterFactory(GsonConverterFactory.create(gson))
        .client(okHttpClient)
        .build()

    /**
     * Provides the [GeoApifyApiService] implementation generated by Retrofit.
     * * This service is used to fetch place predictions and time zone data.
     */
    @Provides
    @Singleton
    fun provideGeoApifyApiService(retrofit: Retrofit): GeoApifyApiService =
        retrofit.create(GeoApifyApiService::class.java)
}