package com.example.smartalarm.feature.clock.framework.di

import com.example.smartalarm.BuildConfig
import com.example.smartalarm.feature.clock.data.remote.api.GeoApifyApiService
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import okhttp3.Interceptor
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import javax.inject.Singleton

/**
 * Hilt module that provides networking dependencies for the application.
 *
 * This module configures and provides:
 * - [Gson] for JSON serialization and deserialization
 * - [HttpLoggingInterceptor] for logging HTTP requests/responses
 * - [Interceptor] to append the Geoapify API key automatically
 * - [OkHttpClient] with interceptors applied
 * - [Retrofit] configured with base URL, OkHttp client, and Gson converter
 * - [GeoApifyApiService] generated by Retrofit
 *
 * Scope:
 * - All provided dependencies are singletons to ensure consistency
 *   and avoid redundant object creation across the app.
 *
 * Usage:
 * - Inject [GeoApifyApiService] or other networking components wherever
 *   network operations are needed.
 */
@Module
@InstallIn(SingletonComponent::class)
object RemoteModule {

    private const val API_PARAM_KEY = "apiKey"
    private const val GEO_APIFY_BASE_URL = "https://api.geoapify.com/"

    /**
     * Provides a [Gson] instance for JSON serialization/deserialization.
     */
    @Provides
    @Singleton
    fun provideGson(): Gson = GsonBuilder().create()

    /**
     * Provides an [HttpLoggingInterceptor] to log HTTP request and response data.
     */
    @Provides
    @Singleton
    fun provideLoggingInterceptor(): HttpLoggingInterceptor =
        HttpLoggingInterceptor().apply {
            level = HttpLoggingInterceptor.Level.BODY
        }

    /**
     * Provides an [Interceptor] that appends the Geoapify API key
     * as a query parameter to every request.
     */
    @Provides
    @Singleton
    fun provideGeoApifyApiKeyInterceptor(): Interceptor = Interceptor { chain ->
        val original = chain.request()
        val originalHttpUrl = original.url

        val newUrl = originalHttpUrl.newBuilder()
            .addQueryParameter(API_PARAM_KEY, BuildConfig.GEO_APIFY_API_KEY)
            .build()

        val newRequest = original.newBuilder()
            .url(newUrl)
            .build()

        chain.proceed(newRequest)
    }

    /**
     * Provides a configured [OkHttpClient] with logging and API key interceptors.
     *
     * @param loggingInterceptor Interceptor for logging HTTP requests/responses.
     * @param apiKeyInterceptor Interceptor to append the Geoapify API key.
     */
    @Provides
    @Singleton
    fun provideOkHttpClient(
        loggingInterceptor: HttpLoggingInterceptor,
        apiKeyInterceptor: Interceptor
    ): OkHttpClient = OkHttpClient.Builder()
        .addInterceptor(apiKeyInterceptor)
        .addInterceptor(loggingInterceptor)
        .build()

    /**
     * Provides a [Retrofit] instance configured with the Geoapify base URL,
     * [OkHttpClient], and [Gson] converter.
     *
     * @param okHttpClient Configured HTTP client.
     * @param gson Gson instance for JSON parsing.
     */
    @Provides
    @Singleton
    fun provideRetrofit(
        okHttpClient: OkHttpClient,
        gson: Gson
    ): Retrofit = Retrofit.Builder()
        .baseUrl(GEO_APIFY_BASE_URL)
        .addConverterFactory(GsonConverterFactory.create(gson))
        .client(okHttpClient)
        .build()

    /**
     * Provides the [GeoApifyApiService] generated by Retrofit.
     *
     * This service is used to fetch place predictions and timezone data.
     *
     * @param retrofit Retrofit instance used to create the service.
     * @return Singleton instance of [GeoApifyApiService].
     */
    @Provides
    @Singleton
    fun provideGeoApifyApiService(retrofit: Retrofit): GeoApifyApiService =
        retrofit.create(GeoApifyApiService::class.java)
}