package com.example.smartalarm.feature.clock.domain.model

/**
 * Domain model representing a geographic place along with
 * its associated time zone metadata.
 *
 * This model is used across the presentation and domain layers
 * to represent search results and user-saved locations.
 *
 * @property id Unique identifier of the place. Typically generated by the local database.
 *
 * @property fullName Fully formatted location name (e.g., "New York, United States").
 * @property primaryName Display-friendly name of the place (e.g., "New York").
 * @property timeZoneId IANA time zone identifier (e.g., "America/New_York").
 * @property offsetSeconds UTC offset in seconds from GMT.
 * @property currentTime Current local time at the place, formatted for display purposes.
 */
data class PlaceModel(
    val id: Long = 0,
    val fullName: String,
    val primaryName: String,
    val timeZoneId: String,
    val offsetSeconds: Int,
    val currentTime: String
)