package com.example.smartalarm.feature.alarm.data.local.entity

import androidx.room.Embedded
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.example.smartalarm.feature.alarm.domain.model.SnoozeSettings
import com.example.smartalarm.feature.alarm.domain.enums.DayOfWeek
import java.time.LocalTime


/**
 * Represents an alarm stored in the database.
 *
 * Each `AlarmEntity` contains all the information needed to schedule and manage
 * an alarm, including its label, time, repeat settings, volume, vibration,
 * sound, snooze configuration, enabled state, and current alarm state.
 *
 * This entity is stored in the `alarm_table` table in Room.
 *
 * @property id The unique identifier for the alarm. Auto-generated by Room.
 * @property label The user-visible label or name of the alarm.
 * @property time The time of day the alarm is set to trigger.
 * @property isDailyAlarm True if the alarm should repeat daily.
 * @property days The specific days of the week the alarm should trigger on,
 *                if `isDailyAlarm` is false.
 * @property volume The volume level for the alarm, typically from 0 to 100.
 * @property isVibrateEnabled True if vibration is enabled for the alarm.
 * @property alarmSound The URI or identifier for the alarm sound.
 * @property snoozeSettings Embedded settings controlling snooze duration
 *                         and maximum number of snoozes.
 * @property isEnabled True if the alarm is currently active/enabled.
 * @property alarmState A string representing the current state of the alarm
 *                     (e.g., "IDLE", "RUNNING", "PAUSED").
 */
@Entity(tableName = "alarm_table")
data class AlarmEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val label: String,
    val time: LocalTime,
    val isDailyAlarm: Boolean,
    val days: Set<DayOfWeek>,
    val volume: Int,
    val isVibrateEnabled: Boolean,
    val alarmSound: String,
    @Embedded
    val snoozeSettings: SnoozeSettings,
    val isEnabled: Boolean,
    val alarmState: String
)