package com.example.smartalarm.feature.alarm.data.local.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey


/**
 * Represents a mission associated with an alarm, stored in the database.
 *
 * Each `MissionEntity` is linked to a parent `AlarmEntity` via the `alarmId` foreign key.
 * Missions define a task the user must complete to dismiss the alarm.
 *
 * This entity is stored in the `mission_table` table in Room.
 * Deleting a parent `AlarmEntity` will automatically delete its associated missions
 * due to the `CASCADE` foreign key behavior.
 *
 * @property id The unique identifier for the mission. Auto-generated by Room.
 * @property alarmId The ID of the parent alarm this mission belongs to.
 * @property type The type of mission (e.g., "math", "shake", "memory").
 * @property difficulty The difficulty level of the mission (e.g., "easy", "medium", "hard").
 * @property rounds The number of rounds or steps required to complete the mission.
 * @property iconResId The resource ID of the icon representing the mission in the UI.
 * @property isCompleted True if the mission has been completed by the user.
 */
@Entity(
    tableName = "mission_table",
    foreignKeys = [ForeignKey(
        entity = AlarmEntity::class,
        parentColumns = ["id"],
        childColumns = ["alarmId"],
        onDelete = ForeignKey.CASCADE
    )],
    indices = [Index("alarmId")]
)
data class MissionEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val alarmId: Int,
    val type: String,
    val difficulty: String,
    val rounds: Int,
    val iconResId: Int,
    val isCompleted: Boolean
)