package com.example.smartalarm.feature.stopwatch.data.manager

import com.example.smartalarm.feature.stopwatch.data.datasource.contract.StopwatchLocalDataSource
import com.example.smartalarm.feature.stopwatch.domain.model.StopwatchModel
import kotlinx.coroutines.flow.StateFlow

/**
 * Contract for a centralized, in-memory coordinator that manages the real-time state
 * of the stopwatch.
 *
 * ### Architectural Role:
 * This interface defines the "Hot" source of truth. It sits between the slow,
 * persistent storage ([StopwatchLocalDataSource]) and the high-frequency
 * execution logic (Ticker). It ensures that regardless of where an update
 * originates, the application has a single, reactive point of access for the
 * current stopwatch session.
 */
interface StopwatchInMemoryStateManager {

    /**
     * A reactive stream of the current [StopwatchModel].
     * * This serves as the primary gateway for the Repository to expose
     * data to upper layers (Domain/UI).
     */
    val state: StateFlow<StopwatchModel>

    /**
     * Retrieves a synchronous snapshot of the current state.
     * * Should be used by the Repository for immediate business logic checks
     * or before initiating a database persistence operation.
     */
    fun getCurrentState(): StopwatchModel

    /**
     * Reconciles the in-memory state with the authoritative database record.
     * * ### Purpose:
     * Used by synchronization managers to push "confirmed" data from
     * persistent storage into memory, ensuring consistency after app
     * launches, process deaths, or external database writes.
     * * @param dbModel The authoritative model retrieved from the local database.
     */
    fun updateFromDatabase(dbModel: StopwatchModel)

    /**
     * Integrates high-frequency, transient updates into the current state.
     * * ### Purpose:
     * Used by the ticker/timer logic to provide millisecond-accurate updates.
     * These updates are transient and are typically not persisted immediately
     * to disk to optimize performance.
     *
     * @param updatedStopwatch The latest model snapshot generated by the live ticker.
     */
    fun updateFromTicker(updatedStopwatch: StopwatchModel)
}