package com.example.smartalarm.feature.alarm.data.mapper

import com.example.smartalarm.feature.alarm.data.local.entity.MissionEntity
import com.example.smartalarm.feature.alarm.domain.enums.Difficulty
import com.example.smartalarm.feature.alarm.domain.model.Mission
import com.example.smartalarm.feature.alarm.domain.model.MissionType


/**
 * Utility object for mapping between domain models and database entities related to missions.
 *
 * Provides functions to convert:
 * - [Mission] domain model to [MissionEntity] database entity for persistence.
 * - [MissionEntity] database entity back to [Mission] domain model for use in application logic.
 */
object MissionMapper {

    /**
     * Converts a [Mission] domain model to a [MissionEntity] database entity.
     *
     * This is used when saving or updating mission data in the database.
     *
     * @param alarmId The ID of the associated alarm to which this mission belongs.
     * @return A new [MissionEntity] with the given alarm ID and mission details.
     */
    fun Mission.toEntity(alarmId: Int): MissionEntity {
        return MissionEntity(
            id = 0, // new entity, id will be autogenerated by the database
            alarmId = alarmId,
            type = type.getName().lowercase(),
            difficulty = difficulty.name,
            rounds = rounds,
            iconResId = iconResId,
            isCompleted = isCompleted
        )
    }


    /**
     * Converts a [MissionEntity] database entity to a [Mission] domain model.
     *
     * This is used when reading mission data from the database to be used in app logic.
     *
     * @return The corresponding [Mission] domain object.
     */
    fun MissionEntity.toDomain(): Mission {
        return Mission(
            type = MissionType.fromName(type),
            difficulty = Difficulty.valueOf(difficulty),
            rounds = rounds,
            iconResId = iconResId,
            isCompleted = isCompleted
        )
    }
}
